/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        navy: {
          950: "var(--navy-950)",
          900: "var(--navy-900)",
          800: "var(--navy-800)",
          700: "var(--navy-700)",
          600: "var(--navy-600)",
          500: "var(--navy-500)",
          400: "var(--navy-400)",
          300: "var(--navy-300)",
          200: "var(--navy-200)",
          100: "var(--navy-100)",
          50: "var(--navy-50)",
          DEFAULT: "var(--navy)",
          deep: "var(--navy-deep)",
        },
        green: {
          800: "var(--green-800)",
          700: "var(--green-700)",
          600: "var(--green-600)",
          500: "var(--green-500)",
          400: "var(--green-400)",
          200: "var(--green-200)",
          100: "var(--green-100)",
          DEFAULT: "var(--green)",
          deep: "var(--green-deep)",
        },
        ink: {
          950: "var(--ink-950)",
          900: "var(--ink-900)",
          800: "var(--ink-800)",
          700: "var(--ink-700)",
          600: "var(--ink-600)",
          500: "var(--ink-500)",
          400: "var(--ink-400)",
          300: "var(--ink-300)",
          200: "var(--ink-200)",
          150: "var(--ink-150)",
          100: "var(--ink-100)",
          50: "var(--ink-50)",
        },
        copper: {
          DEFAULT: "var(--copper)",
          dark: "var(--copper-dark)",
        },
        sand: {
          DEFAULT: "var(--sand)",
          deep: "var(--sand-deep)",
        },
        parchment: "var(--parchment)",
        whatsapp: "var(--whatsapp)",
        danger: { 100: "var(--danger-100)", 600: "var(--danger-600)" },
        success: { 100: "var(--success-100)", 600: "var(--success-600)" },
        warning: { 100: "var(--warning-100)", 600: "var(--warning-600)" },
        info: { 100: "var(--info-100)", 600: "var(--info-600)" },
        text: {
          strong: "var(--text-strong)",
          body: "var(--text-body)",
          muted: "var(--text-muted)",
          subtle: "var(--text-subtle)",
          "on-dark": "var(--text-on-dark)",
          "on-dark-muted": "var(--text-on-dark-muted)",
          brand: "var(--text-brand)",
          accent: "var(--text-accent)",
        },
        border: {
          subtle: "var(--border-subtle)",
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
          brand: "var(--border-brand)",
        },
      },
      fontFamily: {
        display: ["Tajawal", "system-ui", "sans-serif"],
        body: ["Tajawal", "system-ui", "sans-serif"],
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "0px",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "0px",
        "3xl": "0px",
        full: "0px",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        float: "var(--shadow-float)",
        focus: "var(--ring-focus)",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(.2,.6,.2,1)",
        "ease-out-ds": "cubic-bezier(0,.7,.3,1)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "200ms",
        slow: "320ms",
      },
      keyframes: {
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        rise: {
          from: { opacity: "0", transform: "translateY(14px)" },
          to: { opacity: "1", transform: "none" },
        },
      },
      animation: {
        marquee: "marquee var(--marquee-duration,38s) linear infinite",
        rise: "rise .7s cubic-bezier(.2,.7,.2,1)",
      },
    },
  },
  plugins: [],
};
